# Short description (goes below the title; it will also be used in the RSS feed)
description: 别有妖妍胜桃李,攀来折去亦成蹊。

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: http://www.aixixili.com

#paginate: 5

