# Short description (goes below the title; it will also be used in the RSS feed)
description: 别有妖妍胜桃李,攀来折去亦成蹊。

sign: Written by Alan with ♡ 

beian: 沪ICP备15040476号 

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: http://lipan.me

paginate: 10

paginate_path: "/page:num"

# Gems
gems: [jekyll-paginate]

markdown: kramdown
